//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIRApresentacao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIRDataEntities : DbContext
    {
        public CIRDataEntities()
            : base("name=CIRDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anuncio> anuncios { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cidade> cidades { get; set; }
        public virtual DbSet<denuncia> denuncias { get; set; }
        public virtual DbSet<preferencia> preferencias { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
