//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIRApresentacao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class denuncia
    {
        public int Denuncia_id { get; set; }
        public int Anuncio_id { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public int Usuario_id { get; set; }
    
        public virtual anuncio anuncio { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
