//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [Key]
        public int Usuario_id { get; set; }
        public string Nome { get; set; }
        public string email { get; set; }
        public string CPF_CNPJ { get; set; }
        public int Cidade_id { get; set; }
    
        public virtual cidade cidade { get; set; }
    }
}
